---
title: Regression Analysis in R (Part One)
author: Ging Lam
date: '2018-03-25'
slug: regression-analysis-in-r-part-one
categories:
  - statistic
tags:
  - R
  - statistic
  - regression analysis
---


```{r echo=FALSE}
knitr::opts_chunk$set(message=FALSE,tidy.opts=list(width.cutoff=120),comment=NA, prompt=TRUE,fig.height=4, fig.width=4.5) 
```

---------------------

<font size="12"> **There must be a beginning of any great matter,but the continuing onto the end until it be thoroughly finished yields the ture glory任何伟业必有起步,惟苦心孤诣至终,荣耀方降。** </font>

>

<p align="right">  **——— Francis Drake** </p> 

---------------------

### 6.1 Introduction to Regression Analysis
#### Import dataset and run a simple regression model.
```{r}
library(haven)
setwd("E:/D-Storage/courses/Research in R/Lecture Notes by Ging Lam/Advanced Regression Analysis")
china  <- read_dta("ch2_China1996.dta",encoding = "UTF-8")
dim(china)
head(china,5)
china[sample(nrow(china), 5), ] 
names(china)
library(Hmisc)
library(car)
library(Zelig)
label(china)
summary(lm.model0 <- lm(educ_hiy ~ feduc_y,data=china))
confint(lm.model0)
scatterplot(educ_hiy ~ feduc_y,data=china,smooth = F)
summary(lm.model <- lm(educ_hiy ~ feduc_y + meduc_y,data=china))
(glm.model <- glm(educ_hiy ~ feduc_y + meduc_y,data=china))
(zelig.model <- zelig(educ_hiy ~ feduc_y + meduc_y, model = "ls", data = china, cite = FALSE))
library(lm.beta)
lm.beta(lm.model)
```